### ISSUE TITLE
RuntimeError of nnls ceases DYNAMITE

### ISSUE THREAD

**Issue by momomaycry** [dynamics-of-stellar-systems/dynamite#202]
During running of DYNAMITE-BayesLOSVD, one model had a RuntimeError of optimise.nnls, and the weights of this model was not solved.

```
"""
Traceback (most recent call last):
  File "/home/myang/.linuxbrew/Cellar/python@3.9/3.9.2_4/lib/python3.9/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/myang/.linuxbrew/Cellar/python@3.9/3.9.2_4/lib/python3.9/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/myang/dynamite_v2/dynamite/model_iterator.py", line 301, in create_and_run_model
    weight_solver = mod.get_weights(orblib)
  File "/home/myang/dynamite_v2/dynamite/model.py", line 595, in get_weights
    weights, chi2_tot, chi2_kin = weight_solver.solve(orblib)
  File "/home/myang/dynamite_v2/dynamite/weight_solvers.py", line 661, in solve
    solution = optimize.nnls(A, b)
  File "/home/myang/.linuxbrew/Cellar/python@3.9/3.9.2_4/lib/python3.9/site-packages/scipy/optimize/_nnls.py", line 82, in nnls
    raise RuntimeError("too many iterations")
RuntimeError: too many iterations
"""
```
This error ceased the code, and the status of all models in this iteration were False*3.  And I cannot continue running DYNAMITE.

Is there any way to get over this problem?

**Comment by maindlt** [comment]
Closed because any legacy_fortran binary failing will no longer crash DYNAMITE...
