### ISSUE TITLE
Fortran runtime error: End of file

### ISSUE THREAD

**Issue by momomaycry** [dynamics-of-stellar-systems/dynamite#257]
"""
Traceback (most recent call last):
  File "/home/myang/.linuxbrew/Cellar/python@3.9/3.9.2_4/lib/python3.9/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/myang/.linuxbrew/Cellar/python@3.9/3.9.2_4/lib/python3.9/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/myang/dynamite-master/dynamite/model_iterator.py", line 388, in create_and_run_model
    orblib = mod.get_orblib()
  File "/home/myang/dynamite-master/dynamite/model.py", line 668, in get_orblib
    orblib.get_orblib()
  File "/home/myang/dynamite-master/dynamite/orblib.py", line 100, in get_orblib
    self.get_orbit_ics()
  File "/home/myang/dynamite-master/dynamite/orblib.py", line 328, in get_orbit_ics
    raise RuntimeError(text)
RuntimeError: cmd_orb_start exit code 2. ERROR. Message: At line 76 of file iniparam_f.f90 (unit = 13, file = 'infil/parameters_pot.in')
Fortran runtime error: End of file
Logfile: /home/myang/8138-6102/models/orblib_019_000/datfil/orbstart.log.
"""

**Comment by momomaycry** [comment]
It seems to be the consequence of another bug, as I commented in #256
